### PR TITLE
Added initial content layout

### PR DESCRIPTION
**Pull request by codeadict**
Added layout of the different things we can collect about VerneMQ.

### CODE REVIEW

**Comment by codeadict** [comment]
Added some initial layout here @larshesel @ioolkos , will start hunting down for things in a later commit. Please let me know if these categories sound good to you or something else that could be added.

**Comment by ioolkos** [comment]
Looks like a great start to me. Thanks a lot already!

**Comment by larshesel** [comment]
Looks good - think it covers quite a lot already!

**Comment by codeadict** [comment]
Looks like i don't have write access on this one :)

**Comment by larshesel** [comment]
and now?

**Pull request merged**
